/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ChatsHistory: typeof import('./src/components/ChatsHistory.vue')['default']
    DialogBox: typeof import('./src/components/DialogBox.vue')['default']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRate: typeof import('element-plus/es')['ElRate']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Evaluate: typeof import('./src/components/Evaluate.vue')['default']
    FadeTransition: typeof import('./src/components/FadeTransition.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    MoleculeStructure: typeof import('./src/components/MoleculeStructure.vue')['default']
    MolstarRender: typeof import('./src/components/MolstarRender.vue')['default']
    MolstarRender2: typeof import('./src/components/MolstarRender2.vue')['default']
    NavigationBar: typeof import('./src/components/NavigationBar.vue')['default']
    PdbSeletcOrUpload: typeof import('./src/components/PdbSeletcOrUpload.vue')['default']
    Progress: typeof import('./src/components/Progress.vue')['default']
    RecommendationList: typeof import('./src/components/RecommendationList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatisticsIndexs: typeof import('./src/components/StatisticsIndexs.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
